import Navigation from "@/components/Navigation";
import "../styles/reset.css";
import "../styles/GlobalStyle.css";

export const metadata = {
  template: "%s| Best Seller",
  default: "NewYork Times",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  );
}
